server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true